### ISSUE TITLE
System.MissingFieldException: Field 'TranslatedMedalInfo.rank' not found.

### ISSUE THREAD

**Issue by chucklu** [chucklu/HearthBuddyAnalyze#1]
ERROR Logger (null) - [InvokeEvent] Exception during handler: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field 'TranslatedMedalInfo.rank' not found.
   at Triton.Game.Mono.MonoClass.method_5(String string_4)
   at Triton.Game.Mono.MonoClass.method_2[T](String string_4)
   at Triton.Game.TritonHs.Class246.method_31()
   at Triton.Game.PerCachedValue`1.get_Value()
   at Triton.Game.TritonHs.get_MyRank()
   at AutoStop.AutoStopSettings.Reset() in c:\Users\clu\Desktop\Hearthbuddy 0.3.1446.417\Plugins\AutoStop\AutoStopSettings.cs:line 56
   at AutoStop.AutoStop.GameEventManagerOnStartingNewGame(Object sender, StartingNewGameEventArgs startingNewGameEventArgs) in c:\Users\clu\Desktop\Hearthbuddy 0.3.1446.417\Plugins\AutoStop\AutoStop.cs:line 373
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Triton.Game.TritonHs.InvokeEvent(Delegate d, Object[] args)

**Comment by chucklu** [comment]
After  check the source code of 0061e3e6959babde52f2b6536d97dcf1bcbcc56c2990305ecd36103f5669a1b2
https://github.com/chucklu/HearthBuddyAutoConcede/issues/2
method in class TranslatedMedalInfo
```C#
public int GetLegacyRankNumber()
	{
		int num = this.GetMaxStarLevel() - this.starLevel;
		LeagueType leagueType = EnumUtils.SafeParse<LeagueType>(this.LeagueConfig.LeagueType, LeagueType.UNKNOWN, true);
		if (leagueType == LeagueType.NEW_PLAYER)
		{
			LeagueDbfRecord leagueRecordForType = RankMgr.Get().GetLeagueRecordForType(LeagueType.NORMAL);
			if (leagueRecordForType != null)
			{
				num += RankMgr.Get().GetMaxStarLevel(leagueRecordForType.ID);
			}
		}
		return num;
	}
```

The problem might be resolved by fix the following code in TranslatedMedalInfo under namespace  Triton.Game.Mapping
```C#
public int rank
		{
			get
			{
				return base.method_2<int>("rank");
			}
		}
```

**Comment by chucklu** [comment]
When click the reset button on auto stop configuration page
[Application_DispatcherUnhandledException] Unhandled exceptionSystem.MissingFieldException: Field 'TranslatedMedalInfo.rank' not found.
   at Triton.Game.Mono.MonoClass.method_5(String string_4)
   at Triton.Game.Mono.MonoClass.method_2[T](String string_4)
   at Triton.Game.TritonHs.Class246.method_31()
   at Triton.Game.PerCachedValue`1.get_Value()
   at Triton.Game.TritonHs.get_MyRank()
   at AutoStop.AutoStopSettings.Reset() in c:\Users\clu\Desktop\Hearthbuddy 0.3.1446.417\Plugins\AutoStop\AutoStopSettings.cs:line 56
   at AutoStop.AutoStop.ResetButtonOnClick(Object sender, RoutedEventArgs routedEventArgs) in c:\Users\clu\Desktop\Hearthbuddy 0.3.1446.417\Plugins\AutoStop\AutoStop.cs:line 260
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by chucklu** [comment]
[InvokeEvent] Exception during handler: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field 'TranslatedMedalInfo.rank' not found.
   at Triton.Game.Mono.MonoClass.method_5(String string_4)
   at Triton.Game.Mono.MonoClass.method_2[T](String string_4)
   at Triton.Game.TritonHs.Class246.method_31()
   at Triton.Game.PerCachedValue`1.get_Value()
   at Triton.Game.TritonHs.get_MyRank()
   at AutoStop.AutoStopSettings.Reset() in c:\Users\clu\Desktop\Hearthbuddy 0.3.1446.417\Plugins\AutoStop\AutoStopSettings.cs:line 56
   at AutoStop.AutoStop.GameEventManagerOnStartingNewGame(Object sender, StartingNewGameEventArgs startingNewGameEventArgs) in c:\Users\clu\Desktop\Hearthbuddy 0.3.1446.417\Plugins\AutoStop\AutoStop.cs:line 373
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Triton.Game.TritonHs.InvokeEvent(Delegate d, Object[] args)

**Comment by chucklu** [comment]
The previous rank is a field, now we need use a new method.
So we can check the method invoke first for other method
```
public bool IsLegendRank()
{
	return base.method_11<bool>("IsLegendRank", Array.Empty<object>());
}
```

Then add this following new method into
```
public bool GetLegacyRankNumber()
{
	return base.method_11<bool>("GetLegacyRankNumber", Array.Empty<object>());
}
```

Then find the usage of rank , and replace them with the new method.

**Comment by chucklu** [comment]
The code using the rank field
```C#
// Triton.Game.TritonHs.Class246
// Token: 0x06001982 RID: 6530 RVA: 0x000DA818 File Offset: 0x000D8A18
internal int method_31()
{
	RankMgr rankMgr = RankMgr.Get();
	if (rankMgr != null)
	{
		BnetPlayer myPlayer = BnetPresenceMgr.Get().GetMyPlayer();
		if (myPlayer != null)
		{
			MedalInfoTranslator rankPresenceField = rankMgr.GetRankPresenceField(myPlayer);
			if (rankPresenceField != null)
			{
				TranslatedMedalInfo currMedalInfo = rankPresenceField.m_currMedalInfo;
				if (currMedalInfo != null)
				{
					return currMedalInfo.rank;
				}
			}
		}
	}
	return -1;
}

// Triton.Game.TritonHs.Class246
// Token: 0x06001983 RID: 6531 RVA: 0x000DA85C File Offset: 0x000D8A5C
internal int method_32()
{
	RankMgr rankMgr = RankMgr.Get();
	if (rankMgr != null)
	{
		BnetPlayer myPlayer = BnetPresenceMgr.Get().GetMyPlayer();
		if (myPlayer != null)
		{
			MedalInfoTranslator rankPresenceField = rankMgr.GetRankPresenceField(myPlayer);
			if (rankPresenceField != null)
			{
				TranslatedMedalInfo currWildMedalInfo = rankPresenceField.m_currWildMedalInfo;
				if (currWildMedalInfo != null)
				{
					return currWildMedalInfo.rank;
				}
			}
		}
	}
	return -1;
}

```

**Comment by chucklu** [comment]
Find `<>` in TritonHs.Class246, replace it with ChuckInstance in class level first

**Comment by chucklu** [comment]
Then replace the rank field usage
```C#
// Triton.Game.TritonHs.Class246
// Token: 0x06001982 RID: 6530 RVA: 0x000DA748 File Offset: 0x000D8948
internal int method_31()
{
	RankMgr rankMgr = RankMgr.Get();
	if (rankMgr != null)
	{
		BnetPlayer myPlayer = BnetPresenceMgr.Get().GetMyPlayer();
		if (myPlayer != null)
		{
			MedalInfoTranslator rankPresenceField = rankMgr.GetRankPresenceField(myPlayer);
			if (rankPresenceField != null)
			{
				TranslatedMedalInfo currMedalInfo = rankPresenceField.m_currMedalInfo;
				if (currMedalInfo != null)
				{
					return currMedalInfo.GetLegacyRankNumber();
				}
			}
		}
	}
	return -1;
}

// Triton.Game.TritonHs.Class246
// Token: 0x06001983 RID: 6531 RVA: 0x000DA78C File Offset: 0x000D898C
internal int method_32()
{
	RankMgr rankMgr = RankMgr.Get();
	if (rankMgr != null)
	{
		BnetPlayer myPlayer = BnetPresenceMgr.Get().GetMyPlayer();
		if (myPlayer != null)
		{
			MedalInfoTranslator rankPresenceField = rankMgr.GetRankPresenceField(myPlayer);
			if (rankPresenceField != null)
			{
				TranslatedMedalInfo currWildMedalInfo = rankPresenceField.m_currWildMedalInfo;
				if (currWildMedalInfo != null)
				{
					return currWildMedalInfo.GetLegacyRankNumber();
				}
			}
		}
	}
	return -1;
}
```
